# -*- mode: ruby -*-
# vim: set ft=ruby :

CLIENTS = {
  :beer1 => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.107',
  },
  :beer2 => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.108',
  }
}

SERVERS = {
  :indianpaleale => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.106',
  }
}

Vagrant.configure("2") do |config|

  SERVERS.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "4096"]
      end
      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        yum install -y mdadm smartmontools hdparm gdisk lvm2 epel-release tmux ipa-server
      SHELL

    end
  end
end

Vagrant.configure("2") do |config|

  CLIENTS.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        yum install -y mdadm smartmontools hdparm gdisk lvm2 epel-release
      SHELL

    end
  end
end
