---
- name: "template client config : {{ item }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: auditd.conf.j2, dest: /etc/audit/auditd.conf }
  notify:
    - restart-auditd
