* HW 15 Docker
** Задание
   Создайте свой кастомный образ nginx на базе alpine. После запуска nginx должен
   отдавать кастомную страницу (достаточно изменить дефолтную страницу nginx)
   Определите разницу между контейнером и образом
   Вывод опишите в домашнем задании.
   Ответьте на вопрос: Можно ли в контейнере собрать ядро?
   Собранный образ необходимо запушить в docker hub и дать ссылку на ваш
   репозиторий.
   * Задание со * (звездочкой)
   Создайте кастомные образы nginx и php, объедините их в docker-compose.
   После запуска nginx должен показывать php info.
   Все собранные образы должны быть в docker hub
** Выполнение
*** Задание 1
  #+BEGIN_SRC bash
    sudo docker pull rlambda/otus-test-nginx
    sudo docker run --name otus-nginx -d -p 8081:80  rlambda/otus-test-nginx
  #+END_SRC
*** Задание 2
  #+BEGIN_SRC bash
    docker-compose up
  #+END_SRC
*** Ответы на вопросы
    * /Определите разницу между контейнером и образом/
      * образ - неизменяемый слепок будущих контейнеров. Контейнер - запущенный экзеиляр некоторого образа
    * /Можно ли в контейнере собрать ядро?/
      * Так как сборка не предполагает наличия работающего ядра (которого контейнер не имеет), и если в контейнере создано необходимое для сборки окружение, то почему нет?
