name:                lsofM
version:             0.1.0.0
github:              "alexryndin/lsofM"
license:             BSD3
author:              "Alex Ryndin"
maintainer:          "alexnryndin@gmail.com"
copyright:           "Rlambda"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexryndin/lsofM#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  lsofM-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lsofM
    - directory
    - filepath
    - unix
    - split

tests:
  lsofM-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lsofM
