---
# tasks file for nginx

- name: install repo package
  yum:
    state: present
    name:
      - epel-release
  tags:
    - install

- name: install nginx package
  yum:
    state: present
    name:
      - nginx
  tags:
    - install

- name: template new index.html
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
  tags:
    - install
    - configure

- name: configure
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  vars:
    nginx:
      http_port: 8080
  notify:
    - restart
  tags:
    - install
    - configure
