---
all:
  children:
    routers:
      hosts:
        Router1:
          ansible_host: 192.168.12.1
          ansible_ssh_private_key_file: ../.vagrant/machines/Router1/virtualbox/private_key
        Router1:
          ansible_host: 192.168.12.2
          ansible_ssh_private_key_file: ../.vagrant/machines/Router2/virtualbox/private_key
        Router1:
          ansible_host: 192.168.23.2
          ansible_ssh_private_key_file: ../.vagrant/machines/Router3/virtualbox/private_key
